In [1]:
import numpy as np

In [2]:
def theta_1(P_x,P_y):
    return np.arctan2(P_y,P_x)

def theta_2(P_x,P_y,P_z,beta,L_1,L_2,L_3,L_4):
    R=np.sqrt(P_x**2+P_y**2)
    D_r=R-L_4*np.cos(beta)
    D_z=P_z-L_4*np.sin(beta)-L_1
    return -2*np.arctan((2*D_r*L_2 - np.sqrt(- D_r**4 - 2*D_r**2*D_z**2 + 2*D_r**2*L_2**2 + 2*D_r**2*L_3**2 - D_z**4 + 2*D_z**2*L_2**2 + 2*D_z**2*L_3**2 - L_2**4 + 2*L_2**2*L_3**2 - L_3**4))/(D_r**2 + D_z**2 + 2*D_z*L_2 + L_2**2 - L_3**2))

def theta_3(P_x,P_y,P_z,beta,L_1,L_2,L_3,L_4):
    R=np.sqrt(P_x**2+P_y**2)
    D_r=R-L_4*np.cos(beta)
    D_z=P_z-L_4*np.sin(beta)-L_1
    return -2*np.arctan((np.sqrt((- D_r**2 - D_z**2 + L_2**2 + 2*L_2*L_3 + L_3**2)*(D_r**2 + D_z**2 - L_2**2 + 2*L_2*L_3 - L_3**2)) - 2*L_2*L_3)/(D_r**2 + D_z**2 - L_2**2 - L_3**2))

def theta_4(beta,theta_2,theta_3):
    return beta-theta_2-theta_3

def ikine4r(P_x,P_y,P_z,beta):
    L_1=0.137
    L_2=0.105
    L_3=0.105
    L_4=0.095
    T1=theta_1(P_x,P_y)
    T2=theta_2(P_x,P_y,P_z,beta,L_1,L_2,L_3,L_4)
    T3=theta_3(P_x,P_y,P_z,beta,L_1,L_2,L_3,L_4)
    T4=theta_4(beta,T2,T3)
    return np.array([T1,T2,T3,T4])

def ConvRad2An(q,q_Home):
    ListAn=q+q_Home
    for i in range(len(ListAn)):
        ListAn[i]=int(np.interp(ListAn[i],[0, 300*np.pi/180],[0, 1023]))
    return ListAn

    
def ConvGra2An(q,q_Home):
    ListAn=q+q_Home
    for i in range(len(ListAn)):
        ListAn[i]=int(np.interp(ListAn[i],[0, 300],[0, 1023]))
    return ListAn


array([[1.        , 1.        , 1.        , 1.        ],
       [1.02777778, 1.05555556, 1.11111111, 1.13888889],
       [1.11111111, 1.22222222, 1.44444444, 1.55555556],
       [1.25      , 1.5       , 2.        , 2.25      ],
       [1.41666667, 1.83333333, 2.66666667, 3.08333333],
       [1.58333333, 2.16666667, 3.33333333, 3.91666667],
       [1.75      , 2.5       , 4.        , 4.75      ],
       [1.88888889, 2.77777778, 4.55555556, 5.44444444],
       [1.97222222, 2.94444444, 4.88888889, 5.86111111],
       [2.        , 3.        , 5.        , 6.        ]])

In [6]:
q_4=[95.84,92.92,48.34,222.36]
q_Home=[150,150,60,150]

np.multiply(np.subtract(q_4,q_Home),np.pi/180)

L_1=0.137
L_2=0.105
L_3=0.105
L_4=0.095

ikine4r(0.129,-0.179,0.1022,0,L_1,L_2,L_3,L_4)



array([-0.9463319 , -0.93998522, -0.23124155,  1.17122677])

In [68]:
q_4=np.array([0,0,0,0])
q_Home=np.array([150,150,60,150])

H=ConvGra2An(q_4,q_Home)


HomeS=np.array([0,0,0,0,0])
HomeC=np.array([0,0,0,0,70])
AngHome=np.array([150,150,60,150,150])
#Valores análogos de la posición home y los casos. Se obtuvieron desde dynamixel_wizard
PosAnHomeS=ConvGra2An(HomeS,AngHome)
PosAnHomeC=ConvGra2An(HomeC,AngHome)
print(PosAnHomeS)
print(PosAnHomeC)


Zpiso=0.095
Zportaherramientas=0.1


#Valores análogos de la posición home y los casos. Se obtuvieron desde dynamixel_wizard
PosAnHomeS=ConvGra2An(HomeS,AngHome)
PosAnHomeC=ConvGra2An(HomeC,AngHome)



AngPortaHerramientasArriba=ikine4r(0.1,-0.2,Zportaherramientas,0)
AngPortaHerramientasAbajo=ikine4r(0.1,-0.2,Zportaherramientas+0.05,0)


print(AngPortaHerramientasArriba)
print(AngPortaHerramientasAbajo)

[511 511 204 511 511]
[511 511 204 511 750]
[-1.10714872 -0.97106358 -0.18893574  1.15999931]
[-1.10714872 -0.56232242 -0.24466926  0.80699168]


In [73]:
lim=70*np.pi/180
AngArcMinIzq=ikine4r(0.168,0,Zpiso,0)
AngArcMinIzq[0]=lim
AngArcMinDer=ikine4r(0.168,0,Zpiso,0)
AngArcMinDer[0]=-lim

AngArcMaxIzq=ikine4r(0.3,0,Zpiso,0)
AngArcMaxIzq[0]=lim
AngArcMaxDer=ikine4r(0.3,0,Zpiso,0)
AngArcMaxDer[0]=-lim


print(AngArcMinIzq)
print(AngArcMinDer)
print(AngArcMaxIzq)
print(AngArcMaxDer)

[ 1.22173048 -0.93475153 -0.74547649  1.68022802]
[-1.22173048 -0.93475153 -0.74547649  1.68022802]
[ 1.22173048 -1.68880176  1.40264408  0.28615768]
[-1.22173048 -1.68880176  1.40264408  0.28615768]


In [26]:
import time
import roboticstoolbox as rt
import numpy as np

start_time = time.time()

Zpiso=0.095
Zportaherramientas=0.1
Zseguridad=0.15
beta=0

def ConvPosArr2QArr(PosArr):
    [r,c]=PosArr.shape
    QArr=np.zeros([r,c])
    for i in range(r):
        QArr[i,:]=ikine4r(PosArr[i,0],PosArr[i,1],PosArr[i,2],PosArr[i,3])    
    return QArr



def TrajRectDosPuntos(P_i,P_f,N):
    c=len(P_i)
    td=np.zeros([N,c])
    for i in range(c):
        if P_i[i]!=P_f[i]:
            tg=rt.trapezoidal(P_i[i],P_f[i],N)
            td[:,i]=tg.s
        else:
            td[:,i]=P_i[i]
    return td






def CompletoPuntos(Puntos,N):
    [r,c]=Puntos.shape
    Trayectoria=np.zeros([r-1,N,c])
    for i in range(r-1):
        Pi=Puntos[i,:]
        Pf=Puntos[i+1,:]
        Trayectoria[i,:,:]=TrajRectDosPuntos(Pi,Pf,N)

    Arreglo=Trayectoria[0,:,:]
    for i in range(r-2):
        Arreglo=np.concatenate((Arreglo,Trayectoria[i+1,:,:]), axis=0)
        print(Arreglo)
    print(Arreglo)
    return Arreglo



PuntosA=np.array([[0.200,0.150,Zseguridad,beta],[0.200,0.150,Zpiso,beta],[0.250,0.125,Zpiso,beta],[0.200,0.100,Zpiso,beta],[0.225,0.1125,Zpiso,beta],[0.225,0.1375,Zpiso,beta],[0.225,0.1375,Zseguridad,beta]])
PuntosJ=np.array([[0.250,0.100,Zseguridad,beta],[0.250,0.100,Zpiso,beta],[0.250,0.050,Zpiso,beta],[0.250,0.075,Zpiso,beta],[0.200,0.075,Zpiso,beta],[0.200,0.100,Zpiso,beta],[0.200,0.100,Zseguridad,beta]])
PuntosTri=np.array([[0.200,0,Zseguridad,beta],[0.200,0,Zpiso,beta],[0.200,0.050,Zpiso,beta],[0.2433,0.025,Zpiso,beta],[0.200,0,Zpiso,beta],[0.200,0,Zseguridad,beta]])

PuntosRectasParalelas=np.array([[0.200,-0.050,Zseguridad,beta],[0.200,-0.050,Zpiso,beta],[0.200,-0.100,Zpiso,beta],[0.200,-0.100,Zseguridad,beta],[0.225,-0.050,Zseguridad,beta],[0.225,-0.050,Zpiso,beta],[0.225,-0.100,Zpiso,beta],[0.225,-0.100,Zseguridad,beta],[0.250,-0.050,Zseguridad,beta],[0.250,-0.050,Zpiso,beta],[0.250,-0.100,Zpiso,beta],[0.250,-0.100,Zseguridad,beta]])
PuntosR2=np.array([[0.225,-0.050,Zseguridad,beta],[0.225,-0.050,Zpiso,beta],[0.225,-0.100,Zpiso,beta],[0.225,-0.100,Zseguridad,beta]])
PuntosR3=np.array([[0.250,-0.050,Zseguridad,beta],[0.250,-0.050,Zpiso,beta],[0.250,-0.100,Zpiso,beta],[0.250,-0.100,Zseguridad,beta]])
PuntosEQTablero=np.array([[0.200,-0.125,Zseguridad,beta],[0.200,-0.125,Zpiso,beta],[0.200,-0.125,Zseguridad,beta],[0.210,-0.125,Zseguridad,beta],[0.210,-0.125,Zpiso,beta],[0.210,-0.125,Zseguridad,beta],[0.220,-0.125,Zseguridad,beta],[0.220,-0.125,Zpiso,beta],[0.220,-0.125,Zseguridad,beta],[0.230,-0.125,Zseguridad,beta],[0.230,-0.125,Zpiso,beta],[0.230,-0.125,Zseguridad,beta],[0.240,-0.125,Zseguridad,beta],[0.240,-0.125,Zpiso,beta],[0.240,-0.125,Zseguridad,beta],[0.250,-0.125,Zseguridad,beta],[0.250,-0.125,Zpiso,beta],[0.250,-0.125,Zseguridad,beta]])

#Qpuntos


AngHomeGrad=np.array([150,150,60,150,150])
AngHomeRad=np.multiply(AngHomeGrad,np.pi/180)


def ActualizarRegistros(P_o):
    for i in range(len(P_o)):
        #jointCommand('', (i+1), 'Goal_Position', P_o[i], 0.05)
        s=1
    print(P_o)



def RealizarRutina(Puntos,N):
    PuntosTrayectoria=CompletoPuntos(Puntos,N)
    C1=ConvPosArr2QArr(PuntosTrayectoria[:,:])
    [r,c]=C1.shape
    for i in range(r):
        #print(ConvRad2An(C1[i,:],AngHomeRad[0:c]))
        ActualizarRegistros(ConvRad2An(C1[i,:],AngHomeRad[0:c]))
        time.sleep(0.1)



#RealizarRutina(PuntosJ,10)


end_time = time.time()
Tiempo=end_time-start_time
print("\ntiempo de ejecucion: %.2f s" % Tiempo)


tiempo de ejecucion: 0.00 s


In [32]:
def TrajCambioArticulacion(Lim,N):
    tg=rt.trapezoidal(-Lim,Lim,N)
    return tg.s


TrajCambioArticulacion(70,5)


lim=70*np.pi/180
AngArcMinIzq=ikine4r(0.168,0,Zpiso,0)


PosArcMin=np.array([0.168*np.cos(lim),0.168*np.sin(lim),Zpiso,0])
PosArcMax=np.array([0.3*np.cos(lim),0.3*np.sin(lim),Zpiso,0])




array([0.10260604, 0.28190779, 0.095     , 0.        ])

In [28]:
def CompletoPuntos(Puntos,N):
    [r,c]=Puntos.shape
    Trayectoria=np.zeros([r-1,N,c])
    for i in range(r-1):
        Pi=Puntos[i,:]
        Pf=Puntos[i+1,:]
        Trayectoria[i,:,:]=TrajRectDosPuntos(Pi,Pf,N)

    Arreglo=Trayectoria[0,:,:]
    for i in range(r-2):
        Arreglo=np.concatenate((Arreglo,Trayectoria[i+1,:,:]), axis=0)
        print(Arreglo)
    print(Arreglo)
    return Arreglo

qHome=np.array([0.2,0,0.242,0])

qPortaHerramientasArriba=[0.1,-0.2,Zseguridad,0]
qPortaHerramientasAbajo=[0.1,-0.2,Zportaherramientas,0]

N=5
Puntos=np.zeros([2,4])
Puntos[0,:]=qHome
Puntos[1,:]=qPortaHerramientasArriba
#Puntos[2,:]=qPortaHerramientasAbajo
RealizarRutina(Puntos,N)



[[ 0.2        0.         0.242      0.       ]
 [ 0.1859375 -0.028125   0.2290625  0.       ]
 [ 0.15      -0.1        0.196      0.       ]
 [ 0.1140625 -0.171875   0.1629375  0.       ]
 [ 0.1       -0.2        0.15       0.       ]]
[511. 511. 204. 511.]
[482. 532. 160. 534.]
[396. 528.  99. 599.]
[319. 443. 122. 661.]
[295. 401. 156. 669.]


In [9]:

N=5
Puntos=np.zeros([3,4])
Puntos[0,:]=qHome
Puntos[1,:]=np.array([0.1,-0.2,Zseguridad,0])
Puntos[2,:]=np.array([0.1,-0.2,Zportaherramientas,0])
RealizarRutina(Puntos,N)
